"""Изменил тип данных в расписаниях уроков

Revision ID: 0002
Revises: 0001
Create Date: 2023-05-14 02:15:35.814902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menus', schema=None) as batch_op:
        batch_op.create_foreign_key('frgkey', 'users', ['edit_by'], ['id'])
    with op.batch_alter_table('full_lessons', schema=None) as batch_op:
        batch_op.alter_column('grade', type_=sa.String(2))
    with op.batch_alter_table('class_lessons', schema=None) as batch_op:
        batch_op.alter_column('grade', type_=sa.String(2))
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('grade', type_=sa.String(2))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menus', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
