"""кол-во повторов в laundries

Revision ID: 0004
Revises: 0003
Create Date: 2023-05-22 21:08:00.378179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laundries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rings', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laundries', schema=None) as batch_op:
        batch_op.drop_column('rings')

    # ### end Alembic commands ###
