"""'initial'

Revision ID: 5800322ffe02
Revises: 
Create Date: 2023-05-07 05:39:41.082045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5800322ffe02'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menus',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('breakfast', sa.String(), nullable=True),
    sa.Column('lunch', sa.String(), nullable=True),
    sa.Column('dinner', sa.String(), nullable=True),
    sa.Column('snack', sa.String(), nullable=True),
    sa.Column('supper', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_menus_date'), 'menus', ['date'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_menus_date'), table_name='menus')
    op.drop_table('menus')
    # ### end Alembic commands ###
