"""Таблица ролей и её m2m связь с юзерами

Revision ID: 76db5165a92b
Revises: 6150881a53b2
Create Date: 2023-05-10 01:37:43.440877

"""
from alembic import op
import sqlalchemy as sa

from src.utils.consts import Roles


# revision identifiers, used by Alembic.
revision = '76db5165a92b'
down_revision = '6150881a53b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('role')
    )

    for role in Roles:
        op.execute(f'INSERT INTO roles (role) VALUES ("{role.value}")')

    op.create_table('users_to_roles',
    sa.Column('user_id', sa.Integer(), nullable=False, primary_key=True),
    sa.Column('role_id', sa.Integer(), nullable=False, primary_key=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'is_superadmin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_superadmin', sa.BOOLEAN(), nullable=False))
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), nullable=False))
    op.drop_table('users_to_roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
