"""timers_time

Revision ID: 0003
Revises: 0002
Create Date: 2023-09-16 22:00:57.407299

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: Union[str, None] = "0002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "settings",
        sa.Column("washing_minutes", sa.Integer(), nullable=True),
    )
    op.add_column(
        "settings",
        sa.Column("drying_minutes", sa.Integer(), nullable=True),
    )

    op.execute(
        """
    UPDATE settings
    SET washing_minutes = washing_time,
        drying_minutes = drying_time;
    """
    )

    op.alter_column(
        "settings",
        "washing_minutes",
        nullable=False,
    )
    op.alter_column(
        "settings",
        "drying_minutes",
        nullable=False,
    )

    op.drop_column("settings", "washing_time")
    op.drop_column("settings", "drying_time")

    op.add_column(
        "settings",
        sa.Column("washing_time", sa.Time(timezone=False), nullable=True),
    )
    op.add_column(
        "settings",
        sa.Column("drying_time", sa.Time(timezone=False), nullable=True),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("settings", "drying_time")
    op.drop_column("settings", "washing_time")

    op.add_column(
        "settings",
        sa.Column("washing_time", sa.Integer(), nullable=True),
    )
    op.add_column(
        "settings",
        sa.Column("drying_time", sa.Integer(), nullable=True),
    )

    op.execute(
        """
    UPDATE settings
    SET washing_time = washing_minutes,
        drying_time = drying_minutes;
    """
    )

    op.alter_column(
        "settings",
        "drying_time",
        nullable=False,
    )
    op.alter_column(
        "settings",
        "washing_time",
        nullable=False,
    )
    op.drop_column("settings", "drying_minutes")
    op.drop_column("settings", "washing_minutes")
    # ### end Alembic commands ###
