"""olymps

Revision ID: 0006
Revises: 0005
Create Date: 2024-02-13 11:15:08.197596

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0006"
down_revision: Union[str, None] = "0005"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "olymps",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=64), nullable=False),
        sa.Column("subject", sa.String(length=32), nullable=False),
        sa.Column("description", sa.String(length=3584), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_olymps")),
        sa.UniqueConstraint("id", name=op.f("uq_olymps_id")),
    )
    op.create_unique_constraint(op.f("uq_olymps_id"), "olymps", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("olymps")
    # ### end Alembic commands ###
