"""univers

Revision ID: 0007
Revises: 0006
Create Date: 2024-02-13 22:34:27.261506

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0007"
down_revision: Union[str, None] = "0006"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "univers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=64), nullable=False),
        sa.Column("city", sa.String(length=32), nullable=False),
        sa.Column("description", sa.String(length=3584), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_univers")),
        sa.UniqueConstraint("id", name=op.f("uq_univers_id")),
    )
    op.create_unique_constraint(op.f("uq_univers_id"), "univers", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("univers")
    # ### end Alembic commands ###
